### ISSUE TITLE
Hi Metamask family...

### ISSUE THREAD

**Issue by paulpreibisch** [MetaMask/faq#1]
Hi there, we need some more docs for developers... 

I am taking the b9Labs ethereum 101 course, and experimenting with building an AngularJs 1.5 DApp.  I  am curious about  using MetaMask for user authentication.

My dapp is at https://github.com/paulpreibisch/angular1.5_MetaCoin_with_Components.

How might I use MetaMask with with this Dapp?  What are the use cases?

I checked out the two links here: https://github.com/MetaMask/faq, and here: https://blog.metamask.io/developing-for-metamask-with-truffle/ but could use some example Dapps for reference...

Any links / ideas you might be able to point me towards besides the two above?

Kind regards

**Comment by flyswatter** [comment]
To use MetaMask with this setup, you simply use the global `web3` object that is available in the browser scope in browsers that have MetaMask.

It follows the standard Web3 API:
https://github.com/ethereum/wiki/wiki/JavaScript-API

When you check `web3.eth.accounts[0]`, you get the account address the user has currently selected.

If you see no `web3` object, you need some fallback logic, maybe displaying a [badge to download metamask](https://github.com/MetaMask/landing/issues/41).

In terms of sample dapps that work, feel free to flip through our [compatible dapp table](https://docs.google.com/spreadsheets/u/2/d/1KoGlLZJxoCJqDGrX7aMNNoyvcW6FL7VaHU3F2oPA7Vw/edit#gid=0), look for dapps that have a green `yes` in the `support status` column.

I'll leave this issue open as an invitation for us to enhance our developer FAQ with the items you felt like you didn't get here, like sample dapps.

**Comment by flyswatter** [comment]
Extra note: When you submit write requests to the blockchain, like `sendTransaction({from: yourUsersAddress...})`, the user will be prompted by MetaMask to approve the transaction.

**Comment by paulpreibisch** [comment]
Oh very cool, thanks a lot for the quick reply flyswatter!
