### ISSUE TITLE
JSON file doesn't appear to be being recognized

### ISSUE THREAD

**Issue by pearjohn** [MetaMask/faq#102]
Every time I try to use the JSON file to connect my Metamask to MyEtherWallet, it says that key derivation failed, possibly wrong passphrase. I've made two MyEtherWallet accounts and both of them have given me the same message. I know I'm using the right password because I've logged in with the same one and then immediately tried to connect it and had this problem. Are there any possible issues I'm missing?

**Comment by kumavis** [comment]
@pearjohn the password metamask uses is not the "seed phrase password" that MEW asks for. Metamask seed phrases do not have a password.

Also: please open issues on github.com/MetaMask/metamask-extension/issues/new

or better: send an email to support@metamask.io

**Comment by kumavis** [comment]
Also, you can use MEW by connecting metamask

![image](https://user-images.githubusercontent.com/1474978/34730286-cc08dd7e-f513-11e7-8e7f-c6e790713387.png)
