### ISSUE TITLE
Add button not working when adding a token.

### ISSUE THREAD

**Issue by CornGravy** [MetaMask/faq#106]
I type in all the information:

0xf230b790E05390FC8295F4d3F60332c93BEd2
Tron
6 decimals

I click Add and nothing happens. See Screenshot.
https://drive.google.com/file/d/1lUWF0LRs2a0_CyRQutlx8NbbQn1ZffsB/view?usp=sharing

**Comment by tmashuang** [comment]
Please use the email `support at metamask dot io` with any, and all, related questions. It doesn't seem the address provided is a valid address. Are you referring to https://etherscan.io/token/Tronix? If so, the correct contract address to input would be `0xf230b790e05390fc8295f4d3f60332c93bed42e2`.
