### ISSUE TITLE
MetaMask SVG logo

### ISSUE THREAD

**Issue by kirkas** [MetaMask/faq#108]
Is the MetaMask logo available as SVG anywhere? the only thing I could find was a broken old logo done by a 3-party website.

**Comment by danfinlay** [comment]
We have a little web app that lets you grab your own metamask svg:
metamask.github.io/metamask-logo/

**Comment by ivoilic** [comment]
As cool as that 3D web app is it would be really nice to get an standardized 2D SVG.

**Comment by danfinlay** [comment]
[logo-angle.svg.zip](https://github.com/MetaMask/faq/files/1721235/logo-angle.svg.zip)

Weird, Github won't allow an inline svg.
