### ISSUE TITLE
Switching account issues

### ISSUE THREAD

**Issue by reedell** [MetaMask/faq#111]
I am trying to link an account to metamask and Etherdelta. But it isn't letting me beacuse of no key. But the account isn't locked and i can still use it. 

I then get an error that i need to link the proper accounts to meta mask.  This is copies of the errors. It all came for a transaction that was my first time. 

![ed error](https://user-images.githubusercontent.com/35847097/35676720-cac6f71e-0744-11e8-9867-43a4508da5dc.JPG)

![etherdelta error](https://user-images.githubusercontent.com/35847097/35676771-0034d682-0745-11e8-93e9-f7f821dfa349.JPG)

**Comment by danfinlay** [comment]
Please see our guide to EtherDelta accounts:
http://metamask.helpscoutdocs.com/article/8-etherdelta-account-management-tips
