### ISSUE TITLE
MetaMask can't connect to Ganache.

### ISSUE THREAD

**Issue by rrubo** [MetaMask/faq#114]
MetaMask shows blank interface when switching from a test network to localhost: 7545. That said, it seems to interact with smart contract functions, but doesn't update the interface. Weird indeed. I have to disable/enable it to make it work, but once I'm on the Chrome tab where my localhost needs to be injected it goes blank again. Works smooth with Mainnet.

P.S. it was working smooth and fine, but then something happened and this behavior got introduced.

P.P.S. The issue is not observed with the new Beta UI.

![untitled](https://user-images.githubusercontent.com/31670746/37078986-03b004ec-21af-11e8-8fc9-4a90f6a66293.png)

[https://drive.google.com/open?id=1qG6HnhasXpK30_bgicqfNDG_wjpYaZDk](Link to State Logs)

**Comment by danfinlay** [comment]
To debug how this connection was broken, I suspect you would find a crash in the background process. Please check there and report back with what is causing this crash.

https://metamask.helpscoutdocs.com/article/21-how-to-get-logs-and-help-metamask-support-and-diagnose-your-issue

**Comment by danfinlay** [comment]
This is also on the wrong repository. Please submit the correct crash logs to our main repo:

github.com/MetaMask/metamask-plugin
