### ISSUE TITLE
Users ask "Where's my Eth?!". Default network is a test network.

### ISSUE THREAD

**Issue by rolfedh** [MetaMask/faq#14]
Users import their account and see 0.00 ETH. With alarm, they ask "Where's my ETH?!" This experience may trigger fears that their ETH has been stolen.

Actually, it's because the default network is a test network. They have to switch the plugin from using the test network to using the **Ethereum Main Net**.

To mitigate this negative experience, we're going to document this as a top level FAQ item. We should also consider making changing the default to **Ethereum Main Net** soon.

**Comment by flyswatter** [comment]
Another way to avoid this problem would be to do a multi-network survey when an account is first restored, and if only one network has ether, use that one after restore.

Requires that we allow switching networks without reloading, i.e. Isolating our cache logic to a per-network layer.

- Dan

**Comment by rolfedh** [comment]
Hi Dan ( @flyswatter ) When a user adds an account while MetaMask is connected to a test network, the account balance is 1.00 ETH. Suppose the user has a smaller balance 0.5 ETH in their real account. How would your proposal handle that scenario?

**Comment by flyswatter** [comment]
Defaulting to the most-serious used chain seems reasonable.

- Dan

**Comment by billwilson12** [comment]
How can I help others that have this problem they have wallets being made in metamask then they are following the exchange instructions to make a new wallet and to log on with private and public keys which is a big red flag now that MetaMask is round. But then all the transaction disappear into some else's address. On the few I have advised on this I was able to get them to use windows explorer's search with the "hacker stole my money wallet" address and the UTC file belonged to them. But I have that opened the wallet in M.E.W. it shows all the correct balances but will not let them move everything to a clean new wallet tell they learn more. Are not all of the wallet library files the same one for ETH? The interaction with the wallets and dapps or exchanges would appear to need to be seamless. In the last few weeks I have seen hundreds of these and the people feel they have been robbed over the lack of knowledge. https://ethplorer.io/address/0xdf1df1b5879fccfb332eac5973f91be2fab4c4b1#pageSize=100

**Comment by billwilson12** [comment]
I have helped a lot just by getting to load UTC--2017 or the address that took their stuff into the search bar of windows explorer and select the entire computer to search so far they all find wallets then thought they.

**Comment by flyswatter** [comment]
This isn't really an issue anymore, since we sign into Main net by default.

These recent posts by @billwilson12 are unrelated to the original issue, and should be opened in their own topics, please open new issues on the main MetaMask repo:
MetaMask/metamask-extension
