### ISSUE TITLE
Issue in running dapp

### ISSUE THREAD

**Issue by mariam-crissi** [MetaMask/faq#15]
Uncaught (in promise) Error: The MetaMask Web3 object does not support synchronous methods like eth_blockNumber without a callback parameter. See https://github.com/MetaMask/faq/blob/master/DEVELOPERS.md#dizzy-all-async---think-of-metamask-as-a-light-client for details.

How can we resolve this issue?

**Comment by frankiebee** [comment]
What method are you trying to use and are you providing a callback?

That's an error we through because we don't support synchronous methods.
Are thinking for this:
> Using synchronous calls is both a technical limitation and a user experience issue. They block the user's interface. So using them is a bad practice, anyway. Think of this API restriction as a gift to your users.

you can read more about that here https://github.com/MetaMask/faq/blob/master/DEVELOPERS.md#dizzy-all-async---think-of-metamask-as-a-light-client

**Comment by mariam-crissi** [comment]
var bn = web3.eth.blockNumber;

I am using this in my javascript

**Comment by mariam-crissi** [comment]
How can we make it asynchronous??

**Comment by frankiebee** [comment]
Yeah so you have to use the async version which would look something like this:
```javascript
var bn
web3.eth.getBlockNumber(function (blockNumber) {
 bn = blockNumber
})
```

**Comment by mariam-crissi** [comment]
Okay 
Thankyou...
Let me try

**Comment by frankiebee** [comment]
@mariam-crissi https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethblocknumber
here is the docs incase you need it

**Comment by mariam-crissi** [comment]
It worked ....thankyou

**Comment by frankiebee** [comment]
glad to help!
