### ISSUE TITLE
missing tokens 

### ISSUE THREAD

**Issue by rock32871** [MetaMask/faq#21]
i cant seem to find 6 tokens i purchased.  My account shows an error message.  Any thoughts on how I can track this down?

**Comment by tmashuang** [comment]
https://github.com/MetaMask/faq/blob/master/USERS.md#managing-tokens

**Comment by flyswatter** [comment]
Screen shot?

**Comment by Alfredo66** [comment]
I can't find the tokens I purchased last night and today. When I go to their crowdsite I can see my tokens. On Metamask I have just the transactions. When I pressed CLAIM TOKENS nothing happened. Here are some screen shots. This 2 transactions are valued at 1.35 ether for one and 0.10 ether for the other. Any help would be greatly appreciated.

![img_20170628_085807299](https://user-images.githubusercontent.com/29746916/27662815-53084c9a-5c14-11e7-9113-c3eafa28540f.jpg)
![img_20170627_233056771](https://user-images.githubusercontent.com/29746916/27662838-702c7620-5c14-11e7-8a10-0c7b87a2330a.jpg)
![img_20170628_090030691](https://user-images.githubusercontent.com/29746916/27662856-8552e8b8-5c14-11e7-9a36-4a94fc84188c.jpg)
![img_20170628_090245731_burst000_cover_top](https://user-images.githubusercontent.com/29746916/27662874-9ed3154c-5c14-11e7-9337-e727e0a7d1e1.jpg)

**Comment by flyswatter** [comment]
The EOS crowdsale is still underway, my understanding is that they haven't given out any tokens yet, so you need to wait until the end of the first 5 days before you get any tokens.

**Comment by moahad** [comment]
Help.

My EOS tokens have not shown up in my metmask account. I initially tried to claim them via metmask and nothing showed up. Then i thought i'd transfer them to my ether wallet. Now they show as transferred on EOS with a 0 balance. Nothing has shown up in myetherwallet. What have i done wrong?

**Comment by tmashuang** [comment]
https://www.youtube.com/watch?v=lS58BJvxpBg

**Comment by tmashuang** [comment]
![claiming_eos](https://user-images.githubusercontent.com/13376180/27765930-996247a6-5e74-11e7-80cb-bcec783b0e34.png)

**Comment by Alfredo66** [comment]
How do I get on the private network you show on your screen? I am on Metamask and I don't see it

Regards
________________________________

**Comment by tmashuang** [comment]
You don't need to worry about that, what's important is the address and the values, you can be on Mainnet

**Comment by Alfredo66** [comment]
Hi Thomas, I am at the same ADD TOKEN screen but nothing happens when I enter that address. Any ideas?

Alfred
________________________________

**Comment by tmashuang** [comment]
Can you verify you have recieve EOS tokens on etherscan.io your address under token transactions?

**Comment by moahad** [comment]
HI Thomas,

my EOS tokens are showing on on etherscan when i search via my address. However, when i custom add the token in myetherwallet, nothings. I am unsure how i can move these tokens. I want to move them to my kraken exchange account.

**Comment by tmashuang** [comment]
I just tried it out on MyEtherWallet and I get 0 which is correct. Steps I took:
Navigate to MyEtherWallet.com
Send Ether & Tokens
Under Token Balances, Add Custom Token 
Address: 0x86fa049857e0209aa7d9e616f7eb3b3b78ecfdb0
Token Symbol: EOS
Decimals: 18
Click Save

It took me a could tries, but I think the network needed to update. Then I can select the address I want to go, the amount and currency, and gas limit. Make sure your on the right network on MyEtherWallet but selecting one of the three nodes on the top right.

**Comment by Alfredo66** [comment]
Which node is the correct one?

Thank you,
Alfred
________________________________

**Comment by tmashuang** [comment]
Doesn't really matter, I had it on MyEtherWallet.

**Comment by Alfredo66** [comment]
Thank you again. I hope it works for me and you too.
________________________________

**Comment by Alfredo66** [comment]
I did as you mentioned but afterwards it shows 0 tokens
________________________________

**Comment by tmashuang** [comment]
I see from your screenshots that you haven't claimed your tokens from the eos.io website.

**Comment by Alfredo66** [comment]
Hi Thomas, it might be that, even though I am Canadian, I happen to be in the USA. Some how the EOS system won’t let me in anymore. It did let me in initially, but not now. The computer I am using has a US IP address. I guess I’m screwed. I sent a message to Block.one’s support center. I hope they have an acceptable answer. I hope they will return my funds as I have documentation. If you know anyone there maybe you can put a word in for me – oh well.

Cheers mate,
Alfred

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
