### ISSUE TITLE
Ether transaction not showing on MetaMask

### ISSUE THREAD

**Issue by Ljooks** [MetaMask/faq#25]
Hi,

I've recently transferred Ether to MetaMask for the first time. I've waited for about an hour and there is no transaction information in MetaMask or Etherscan, although my wallet says the transaction has completed.

Is this normal? Should I just keep waiting and see what happens? I've checked the MetaMask address and it has been inputted correctly.

I am on Etherium Main Net and not a test network.

Thank you

**Comment by Zanibas** [comment]
Incoming transactions are not currently recorded in MetaMask, unfortunately. However, if the transaction was successful, then Etherscan should have definitely picked up on it.

Are you sure you're examining your accounts through the "Main Ethereum Network" as seen in the upper left hand corner? On Etherscan, are you looking through `etherscan.io` instead of possibly `kovan.etherscan.io` or some other subdomain?

**Comment by Zanibas** [comment]
Sorry, I just read your other comments, so I'm reposting this reply:

We do not currently show incoming transactions on MetaMask, unfortunately, but it's very puzzling that Etherscan is not picking up on your transaction. Are you sure that the Etherscan domain is for the Main Net and not for a test network?

**Comment by Ljooks** [comment]
Thank you for your reply.

I clicked on the information button on Etherium Main Net and was directed to Etherscan. The address is the same. Bummer!

**Comment by Zanibas** [comment]
Interesting--have you checked that there was an outgoing transaction from your source address to confirm that funds were indeed transferred _somewhere_?

**Comment by Ljooks** [comment]
Yes. There was a competed outgoing transaction but no Txid.

**Comment by Zanibas** [comment]
As in there was no transaction hash? Is the outgoing transaction able to be located on etherscan? As in, does looking up your source address on etherscan show an outgoing transaction?

I'm sorry if these questions seem demeaning--but they really help clarify the situation.

**Comment by Ljooks** [comment]
The transaction has finally shown up in Etherscan as pending. Phew! Thanks for your help. It tooks quite a while so got me worried.

**Comment by Zanibas** [comment]
Alright, that's great to hear! The network can be painfully slow at times! Obviously as a community, we need to work more on more responsive UX to help calm users fears about long waiting times!

**Comment by Ljooks** [comment]
Thanks for all your help!
