### ISSUE TITLE
Kraken exchange

### ISSUE THREAD

**Issue by aleleo69** [MetaMask/faq#27]
Would it be possible to add Kraken to the exchanges?

**Comment by flyswatter** [comment]
I'm not sure kraken supports direct to ether account purchases, my understanding is they are an exchange, while we actually don't have exchanges as much as ways of purchasing ether.

**Comment by flyswatter** [comment]
Closing because I think Kraken has an instant-purchase widget. If they do, please post it in a new issue on MetaMask/metamask-plugin, our main repository.
