### ISSUE TITLE
ETH not received

### ISSUE THREAD

**Issue by tomvienna** [MetaMask/faq#29]
Hello,

I just send 50 Euros from my Breadwallet to the metamask,

the ETH show up in the history +0.163 ETH

but not in the balance on top.

I waited now for about an hour, on my breadwallet the transaction showes up as sent.

**Comment by tmashuang** [comment]
could you DM me your address on slack? http://slack.metamask.io

**Comment by flyswatter** [comment]
If you look up your address on etherscan, do you see the transaction? If not, it's the sender's (breadwallet's) fault.

**Comment by tomvienna** [comment]
now the eths show up, but on etherscan the transaction is still not findable... thank you for your help
