### ISSUE TITLE
Document metamask identification

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/faq#3]
I hear you can check for this header `Origin=chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn`?  Does that mean we're overwriting origin headers?

In any case, if there's a way to identify metamask clients, would be nice to document.

**Comment by abitrolly** [comment]
Fixed by https://github.com/MetaMask/faq/blob/master/detecting_metamask.md ?

**Comment by kumavis** [comment]
Adding a note on `web3.currentProvider.isMetaMask`
