### ISSUE TITLE
ETH transfer to the wallet failed and ETH disappeared.

### ISSUE THREAD

**Issue by Marty9000** [MetaMask/faq#30]
Hello,

I tried to transfer my Ethers to the my metamask wallet from CEX.io and Poloniex. But all the transfers has failed but also my ethers removed from my balance.

Below my operations did not added to my wallet. And interestingly, when you check transaction ID's on etherscan.io , these transaction are not even shown (you can try check on etherscan.io)

with poloniex
Address (my metamask adress): 0x5fd854D6dD295BbD6938Bdf8e9e3C8C9673AbaCe
Txid: 0x514d23888620a43d0bb2a702bb8c187d9fe00e78ea4436ca67bdf52a9e910f08
Amount: 0.01 eth (I just send low amounts because for check) (Poloniex takes only 0.005 eth as fee, so there has to deposit 0.005 eth but its not deposited.)
ETHERS DID NOT SEND TO MY METAMASK WALLET

with CEX.io
Address (my metamask adress): 0x5fd854D6dD295BbD6938Bdf8e9e3C8C9673AbaCe
Txid: 0x8e1314221182b619c961f0adc3720708b1eb7b113742774518335dab8b4a14e2
amount: 0.05 eth (I just send low amounts because for check)
Txid: 0xbc0027031e1ffc73d492a56e98411fec87451b8521f0282250404a4341731128
amount: 0.011 eth (I just send low amounts because for check)
ETHERS DID NOT SEND TO MY METAMASK WALLET

I add screenshots for proof.

![ekran resmi 2017-06-21 16 19 28](https://user-images.githubusercontent.com/29602903/27386156-a2cb7b8e-569d-11e7-9d45-f30845728147.png)
![ekran resmi 2017-06-21 16 19 00](https://user-images.githubusercontent.com/29602903/27386167-a7f1ee68-569d-11e7-914c-53e4fe8e978c.png)

there is only 0.002 ethers in my metamask wallet that my friend send me again for just check. wallet -to-> wallet is OK. But above operations is not.

Please help,
Kind regards.

**Comment by flyswatter** [comment]
If a transfer is never sent, and never visible on etherscan, that is the sender's fault. You should contact the exchanges you were sending from.

**Comment by a0903l22** [comment]
https://etherscan.io/address/0x7DB790d7C12A6782B3c74ec079712a43d92dc0C3
i have some failed transaction and ETH disappeared
