### ISSUE TITLE
Transaction not recieved

### ISSUE THREAD

**Issue by fervall** [MetaMask/faq#31]
Hi, 
I made a withdrawal yersterday from poloniex to my MetaMask and the transaction is not registered.

Can you help me please.
Thanks

**Comment by tmashuang** [comment]
Metamask does not currently support viewing incoming transactions. Please view you account on etherscan to see if the transaction was received. If not, contact Poloniex for your the transaction status.

**Comment by Marty9000** [comment]
Dear Fervall,

May I ask you which amount you tried to withdraw and lost? 
Did you able to look your transaction status at etherscan.io?
(by the way I'm not authorized. just asking, same thing happened to me.)

**Comment by fervall** [comment]
Hi Marty9000, I withdrew 40 dollars from poloniex, I look for the transaction on etherscan.io but does'nt appear.
I had to open a support ticket on poloniex

**Comment by flyswatter** [comment]
@fervall, the entire network is completely congested at the moment. It will probably take at least another day before transactions are processed smoothly again.

**Comment by kumavis** [comment]
if you still have questions, please email support@metamask.io
