### ISSUE TITLE
Reveal for ens domain is not going through

### ISSUE THREAD

**Issue by mobley23** [MetaMask/faq#32]
I have multiple reveal transactions that I've been submitting at higher than recommended gas prices, up to 140 gwei, and none of them are going through. Please help.

**Comment by alevasa** [comment]
I have exaclty the same problem and one of my bids the reveal fase ends in 3 hours can some one help us?

**Comment by mobley23** [comment]
Found a solution posted on reddit, https://www.reddit.com/r/ethereum/comments/6i9w5y/reveal_not_working_with_metamask_on_ens_help/

You need to switch the metamask network to a different one, then switch it back.  Should work after that.  It worked for me, and I had to periodically do that switch back and forth.  I'd recheck that the reveals went through and seemed to work.

**Comment by alevasa** [comment]
tks for the tip I did two things, changed network and changed back to
Ethereum Main Net and increased gas price to 51 and it worked :-)

2017-06-22 14:01 GMT-03:00 mobley23 <notifications@github.com>:

**Comment by ashtonware** [comment]
thanks @mobley23 !!

**Comment by myetherdomain** [comment]
Thanks, changing network and switching back works here too!

**Comment by kumavis** [comment]
if you still have questions, please email support@metamask.io
