### ISSUE TITLE
Cannot send ETH to another wallet

### ISSUE THREAD

**Issue by matwxx** [MetaMask/faq#34]
I am a noob. I was trying to send my ETH from Metamask to another wallet. I put in the wallet address and  amount of ETH then send. On the next page I put in 200,000 gas limit and 50 Gwei. And I confirm thats what gas is enough from my account to send out. The transaction never went out. What did I do wrong?

**Comment by tmashuang** [comment]
What does it say on your transaction history?

**Comment by matwxx** [comment]
> 

> ![image](https://user-images.githubusercontent.com/29326022/27441789-1e523dd4-57a1-11e7-88fb-23f5d4135e99.png)

**Comment by matwxx** [comment]
> 
![image](https://user-images.githubusercontent.com/29326022/27441863-4e2396d4-57a1-11e7-95a5-b916584885f9.png)

**Comment by tmashuang** [comment]
You have to reset your nonce. Uninstall, reinstall, and loggin with your Seed Phrase through "I forgot my password".

**Comment by matwxx** [comment]
Why do I need to use the "i forgot my password?

**Comment by flyswatter** [comment]
Because the "restore from seed" feature is currently labeled poorly. We'll fix that.

**Comment by matwxx** [comment]
Oh ok. Thanks. And how do I uninstall the metamask?

**Comment by flyswatter** [comment]
You can right click the fox, "Manage extensions", and uninstall from that page.

**Comment by matwxx** [comment]
Click the trash icon to remove?

**Comment by flyswatter** [comment]
Yes.

**Comment by matwxx** [comment]
I deleted and add the it back again. Now I click on import existing Den.  Where can I find the I forgot my password?

**Comment by matwxx** [comment]
> 
![image](https://user-images.githubusercontent.com/29326022/27442663-69960210-57a3-11e7-9100-5775060f7174.png)

**Comment by flyswatter** [comment]
Oh I'm sorry, Thomas's explanation was incorrect. If you uninstall, you can restore from seed with the view you are looking at. If you didn't uninstall, you could've Locked MetaMask to see the "Forgot password" link.

**Comment by matwxx** [comment]
Umm...So what should I do now?

**Comment by flyswatter** [comment]
Enter your seed phrase into that box, with a new password.

**Comment by matwxx** [comment]
Ok done. So I can send transaction now or should I lock metamask to see the forgot password link?

**Comment by flyswatter** [comment]
You should be able to send a transaction now.

**Comment by matwxx** [comment]
Ok. What is the require gas limit and gas price to send eth to myetherwallet?

**Comment by flyswatter** [comment]
Leave the gas limit where it is. Gas price you might want to consult ethgasstation.info/ for now, because the network is very congested. We will have a more intelligent default soon.

**Comment by matwxx** [comment]
Ok. Thanks for your help. Appreciated.

**Comment by matwxx** [comment]
Hi, I have spent 0.22 eth on paying txn fees on this matter. And I don't see instructions that I have to uninstall, reinstall to send my txn. I think this is your fault for not showing instructions on this matter. You will pay me back my txn fee back?

**Comment by flyswatter** [comment]
No, absolutely not. As I wrote in the other issue you opened, reinstalling had nothing to do with your transactions getting rejected. The fact that gas was burned is proof that the transactions were processed, you were just late to the sale.
