### ISSUE TITLE
Recover seed using private key?

### ISSUE THREAD

**Issue by cryptopana** [MetaMask/faq#36]
Hi guys.

Like it says on the subject of this, I wrote down the seed when I registered on MetaMask, but I lost the paper where I had written it down.

I do have my private key though, so would that be enough to recover my account in case I lose access to it or something?
I guess another way of asking this question is: Am I ok if I only have my private key, and not my seed?

Thanks!

**Comment by flyswatter** [comment]
No, sorry, the many account private keys are derived from the seed phrase, but the seed phrase cannot be derived from them.
