### ISSUE TITLE
In Firefox (macOS), attempting to add account via JSON causes the Metamask dropdown to close, preventing import

### ISSUE THREAD

**Issue by mtchllbrrn** [MetaMask/faq#38]
Here are the steps taken to replicate to the failure:

Open Metamask dropdown > hamburger icon (top-right) > Import Account > Select "JSON" from the dropdown > Browse

As soon as the browser opens the file picker, the Metamask dropdown closes.  This cancels the import process, ultimately preventing JSON import altogether.

I've done the same in Chromium and found that it works as expected.

I'm running Firefox v53.0.3 (64-bit), macOS v10.11.6.

**Comment by flyswatter** [comment]
We're aware of this bug and have reported it to the Chromium team, as it only happens on Ubuntu.

A workaround for importing is to visit this URL in your browser, to view the MetaMask popup as a browser tab:
chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/popup.html

**Comment by flyswatter** [comment]
Interestingly, this is apparently on our FAQ, too:

https://github.com/MetaMask/faq#q-i-cant-use-the-import-feature-for-uploading-a-json-file-the-window-keeps-closing-when-i-try-to-select-a-file

We have a better, searchable knowledge base coming soon!!!

**Comment by tmashuang** [comment]
We'll open up a support ticket to Firefox for this issue.

**Comment by mtchllbrrn** [comment]
@flyswatter I'm not sure if I made it clear, but I'm encountering this bug in Firefox, macOS.  Metamask running in Chromium works just fine.

**Comment by flyswatter** [comment]
Oh wow, sorry, I skimmed the bug because it was known on Ubuntu. Thanks for that report!  Opening on our main issue tracker.
https://github.com/MetaMask/metamask-plugin/issues/1686

**Comment by Lupul** [comment]
In firefox the direct add-on address is : (I don't know if this address is also static as the Chrome one)
moz-extension://f26c0aae-c71e-48fb-957f-e5f145d35c41/popup.html

**Comment by seizu** [comment]
On Firefox go to the address bar enter **about:debugging** 
scroll down to metamask plugin and copy the **UUID** and prepare this link
moz-extension://**--Replace--UUID--**/popup.html
