### ISSUE TITLE
Missing Tokens from Yesterday and today during Crowdsale using interface with Metamask

### ISSUE THREAD

**Issue by Alfredo66** [MetaMask/faq#39]
I mistakenly attached screenshots on rock32871's issue. Any help would be greatly appreciated.

**Comment by flyswatter** [comment]
I suspect you're talking about the EOS crowdsale. That sale hasn't ended yet, tokens haven't been distributed yet, but you should check in with EOS to be sure, since they're the ones distributing their tokens.

**Comment by Alfredo66** [comment]
Thank you Dan, I left them a message but no word back yet. I hope they throw me a bone.

Alfred
________________________________

**Comment by Alfredo66** [comment]
Hi Dan,
I bought into the EOS ICO using the Metamask interface, but I understand that I will still have to register a public key. How do I do it via Metamask? I am supposed to claim my EOS tokens Saturday and Sunday.

Regards,
Alfred
________________________________

**Comment by flyswatter** [comment]
My understanding is that EOS token distribution is managed from their page. Please let me know the answer if you find out, you're not the only person to ask.

https://eos.io/distribution/

**Comment by samyyaga** [comment]
Hey Dan, I've taken part in EOS token distribution, and I was able to receive 12.5 tokens in my MetaMask wallet...  However, I participated in the EOS crowdsale 3 days ago, and have not received the equivalent tokens...

**Comment by danfinlay** [comment]
Have you checked your token balance on [etherscan](https://etherscan.io/)?
Maybe you just haven't told MetaMask to track EOS tokens yet?
http://metamask.helpscoutdocs.com/article/11-adding-confirming-and-locating-your-erc20-tokens

If you still see no sign that you have your tokens, contact EOS! They're the ones who promised them!
