### ISSUE TITLE
how to connect to a custom RPC?

### ISSUE THREAD

**Issue by FugueWeb** [MetaMask/faq#41]
Hello Metamask team,

Can you please provide some insight on how to properly connect to a `custom RPC` (I suggest adding it to the [Metamask Users FAQ](https://github.com/MetaMask/faq/blob/master/USERS.md), would even be willing to make the pull request once I figure it out). I am running a private geth node on an Ubuntu 16 AWS EC2 instance and I am unclear on what URL or URI I am supposed to include in the `custom RPC` field. I have the DNS link, which opens to the standard Apache `index.html` homepage (so I know the server is running), and I can do transactions in `geth` from the command line, but I'm not sure where to go from there to connect `geth` to Metamask.  I can connect to Rinkeby just fine as well so I have no reason to believe Metamask is not working.

This is what gets me into the console, and I have tried appending the port numbers to the DNS link with no success (the loading gif for the network connection just spins). Any help or insight or reference to appropriate documentation would be very much appreciated. Thanks!

`geth --identity "my-private-node" --rpc --rpcport "8080" --rpccorsdomain "*" --datadir "~/name-of-my-private-chain/" --port "30303" --rpcapi "db,eth,net,web3" --networkid 1999 console`

**Comment by tmashuang** [comment]
Click the top left network tab and custom rpc.

**Comment by tmashuang** [comment]
Click the top left network tab and custom rpc.

**Comment by FugueWeb** [comment]
Hello @tmashuang, thanks for the fast response. Please note, the question is not how or where to input the URL in Metamask, it is about how do I know exactly what URL/URI to input based on my `geth` node. I have already tried inputing several links with no success.

**Comment by tmashuang** [comment]
<img width="485" alt="screenshot 2017-07-01 04 05 00" src="https://user-images.githubusercontent.com/13376180/27761536-7eb10080-5e12-11e7-84ec-cc1197f80b46.png">

**Comment by FugueWeb** [comment]
I'm seeing this in my console, but I'm not trying to connect to localhost. I'm looking for a link that would allow anyone with this link to be able to connect to the node (I recognize this has security implications, which I plan to address). Something like `http://my-aws-ec2-info.amazonaws.com:port-number` or similar. I guess I'm at a loss for what steps to take in order to trouble shoot this issue, since everything seems to be working correctly.

What are the equivalent links used to connect to Ropsten or Rinkeby?

**Comment by FugueWeb** [comment]
I'm pretty sure I'll find the answer I'm looking for by understanding the [`admin` configurations](https://github.com/ethereum/go-ethereum/wiki/Management-APIs#admin) better in `geth`.
