### ISSUE TITLE
How to remove a Token added to MetaMask, Token is still in ICO mode and thus unrecognized

### ISSUE THREAD

**Issue by ddkdlk** [MetaMask/faq#42]
I added a token to Metamask, and now etherdelta won't let me log into exchange do to unrecognized token in metamask chrome plug-in. I see how to add tokens, but is there a way to remove them from wallet till they are active? Thank you for all your time, effort, and patients.

**Comment by flyswatter** [comment]
I don't understand why Etherdelta won't let you log in, but it definitely is not related to whether you added a token to MetaMask to view in the tokens tab.

We have not yet added a way to remove a token from the list, but it should not interfere with EtherDelta.

**Comment by flyswatter** [comment]
The "unexpected token" SyntaxError error you got does not refer to an Ethereum token, but a JavaScript character.

I believe you're running an older browser, I think you'll fix this problem by updating it.
