### ISSUE TITLE
Eos tokens don't show up in my MetaMask account..

### ISSUE THREAD

**Issue by chriszacharia** [MetaMask/faq#43]
I press on add token. i token symbol  i put: EOS, in decimals : 18, and in address i put the same address as my ethereum address . it tells me that no tokens found...
What can i do to add my EOS Tokens ?? I have a confirmation from eos team that they have sent me the tokens to my account: 0xb3faF233591E91D433D44FA7C4Ca5d3Bfc9D118a

Thanks for your help

**Comment by flyswatter** [comment]
To add a token you need the token address. Did you learn the EOS token address? Lots of people have been asking this.
