### ISSUE TITLE
Metamask Transaction not yet received

### ISSUE THREAD

**Issue by catchganu** [MetaMask/faq#45]
transferred ETH from coinspot.com.au 1 hr ago and it is yet to be received. Is it normal ? I am newbie and this is my first transfer, freaking out.... please suggest on what is average time for transaction to reflect in metamask. 

In coinspot.com.au it shows as successful, but my metamask balance is Zero. Please suggest. thanks

**Comment by Marty9000** [comment]
Transfers can be take some time due to how much gas given (more gas, faster process). By the way you say that is from coinspot (Idk its default gas limit), keep calm it will be added your metamask wallet soon.
