### ISSUE TITLE
IDICE balance not visible on Metamask

### ISSUE THREAD

**Issue by khankasi** [MetaMask/faq#46]
Dear i just did a IDICE TOKEN transfer to my Metamask address : 0xadE0093AeDF7A88E1687eB0AadD0B3DB025EaB2C

but cannot see any balance? can you help please

**Comment by flyswatter** [comment]
Here's our current guide on managing tokens in MetaMask: https://consensyssupport.happyfox.com/kb/article/4-managing-tokens

**Comment by khankasi** [comment]
thanks alot Flyswatter :) very helpfull reply.. but when i research for my token on ETH it says '' waiting to be mined'' so maybe after when the mining is done i can check this process to see the balance hopefully.. thanks alot i reply again if i see the balance 👍

**Comment by flyswatter** [comment]
Sorry, where do you see "waiting to be mined"? You shouldn't see that anywhere in MetaMask. Could you send a screen shot?

In MetaMask, in the tokens tab, you should be able to press `+`, then enter the token address, then add the token. Is that not working?

**Comment by khankasi** [comment]
OK no problem, i saw that on TX status,
It says your transaction was located in TX POOL of the node you are connected to.  Currently pending (waiting to be mined.    However, the Metamask when I added the given address By IDice with decimal didn't do anything at all. Maybe it won't function as yet?

**Comment by khankasi** [comment]
Hurray! Got the token on my Metamask just now thanks

**Comment by flyswatter** [comment]
That TX status represents a transaction you have sent, I see. Glad you worked it out.
