### ISSUE TITLE
metamask

### ISSUE THREAD

**Issue by denisenicola** [MetaMask/faq#47]
.I need getting my money out of metamask. 
Metamask Keeps telling me i have insufficent funds and i have over 200. What do i do?  I am Freaking out ! I would like my money today.  Please help.

**Comment by flyswatter** [comment]
I replied on the other issue you opened.

**Comment by flyswatter** [comment]
It is here: https://github.com/MetaMask/metamask-plugin/issues/1753#issuecomment-313730073
