### ISSUE TITLE
cant buy

### ISSUE THREAD

**Issue by blindman1** [MetaMask/faq#48]
My ether account shows 4 ether but metemask says it is not in there and is not letting me buy anything.

**Comment by tmashuang** [comment]
Can you provide your public address? Or you can etherscan your account and find more details of your account. If you are still unable to find the issue, please message your state logs to https://consensyssupport.happyfox.com/staff/kb/article/15-copying-state-logs

**Comment by blindman1** [comment]
0x1ad4945f3607d57dcc8b6141adfc18cced044356


Nick Thille





-----Original Message-----

**Comment by tmashuang** [comment]
I am interested in where it says you have 4 ether. This is your balance on etherscan.
https://etherscan.io/address/0x1ad4945f3607d57dcc8b6141adfc18cced044356
Is this the same balance Metamask is showing as well?

**Comment by blindman1** [comment]
See attached photo of screen shot


Nick Thille 






-----Original Message-----

**Comment by tmashuang** [comment]
Your screenshot is not showing when you email it.

**Comment by blindman1** [comment]
hope this helps



Nick Thille 







-----Original Message-----

**Comment by blindman1** [comment]
It seems that my 4 ether and PTT have vanished??


Nick Thille 
Ultrasonic Blind Services 
310-371-2258 
www.ultrasonicblindservices.com 
Jesus is the way the truth and the life.





-----Original Message-----

**Comment by tmashuang** [comment]
I just see VERI and Status tokens were the only tokens your account was associated with. If you're using Etherdelta contact their support for more information with your transactions.

**Comment by blindman1** [comment]
Are my 4 ether and 100 PPT  gone? I dont understand how etherscan can show a different balance from my ether-delta account?


Nick 






-----Original Message-----

**Comment by tmashuang** [comment]
Etherdelta has a different address than your Metamask address

**Comment by blindman1** [comment]
How do I get it resolved? Thank you for your time

**Comment by tmashuang** [comment]
There was no indication of a transaction for 4 eth, just 10 eth deposited and two separate transactions to etherdelta, with the address provided. There is also no indication of the address ever having PPT.

**Comment by flyswatter** [comment]
It's possible EtherDelta is showing the balance of tokens you have deposited into their exchange. In this case, you are not holding those tokens, you've given them over to their smart contract, and need to withdraw them to hold them yourself. That said, we don't manage EtherDelta, so you should contact them for specific support on their exchange. Your account legitimately does not have tokens, and you probably put them in EtherDelta.
