### ISSUE TITLE
MetaMask

### ISSUE THREAD

**Issue by Severence** [MetaMask/faq#51]
Hi could anyone please help me...I purchased some PPT in EtherDelta the amount of PPT is still showing in there..but its just the amount of PPT I bought..... I can no longer transfer it withdraw it or sell it.....I know its there as I checked Etherscan and it was transfered back into my account...1) Why is it not showing in my Tokens and 2) how do I withdraw it  ..Any  Help

**Comment by flyswatter** [comment]
Here’s our current guide on managing tokens in MetaMask: https://consensyssupport.happyfox.com/kb/article/4-managing-tokens

We only show some popular tokens by default, and it looks like we do not show PowerPoint tokens (or whatever that stands for) by default.

In that guide, you'll see how to add an unknown token by address.

We don't currently have a token sending feature, but you can send tokens from MetaMask by visiting a token sending interface, the guide I linked to has a few listed.

**Comment by Severence** [comment]
Thanks Dan...but the link you provided doesnt seem to how anything other
than a Search feature..and when i type help with setting up tokens in
metamask ..nothing shows...Do you have another sire..Regards  John

**Comment by flyswatter** [comment]
That's very strange, I don't know why that link stopped working. Try this one:
http://metamask.consensyssupport.happyfox.com/kb/article/4-managing-tokens

**Comment by Severence** [comment]
Thanks Dan...I manged to work it out...I am a noob so using MetaMask for
the 1st time was interesting..Anyway it was simple once i entered the
address for the PPT Tokens they showed up instantly,,,But Thanks for you
quick response and helping with my query..Kindest Regards  John
