### ISSUE TITLE
Event onAccountChange

### ISSUE THREAD

**Issue by rstormsf** [MetaMask/faq#52]
is there an Event onAccountChange that will notify a Dapp that the default account has been changed?

**Comment by flyswatter** [comment]
Not yet, but hopefully eventually. For now there's just this awful hack:
https://github.com/MetaMask/faq/blob/master/DEVELOPERS.md#ear-listening-for-selected-account-changes

**Comment by rstormsf** [comment]
yeah I figured. Thanks man. @flyswatter

**Comment by frankiebee** [comment]
@rstormsf you can also do *BUT IT ONLY WORKS WITH METAMASK NOT MIST SO MAKE SURE THE FUNCTION IS THEIR first* 
```js
let selectedAddress = web3.currentProvider.publicConfigStore.getState().selectedAddress
// this will get called any time the publicConfigStore updates eg: selectedAccount changes or the 
//network
if (web3.currentProvider.publicConfigStore) { 
  web3.currentProvider.publicConfigStore.subscribe((state) => {
    if (selectedAddress !== state.selectedAddress) {
      //do stuff here to react to the address changing
      selectedAddress = state.selectedAddress
    }
  })
} else {
// do polling ¯\_(ツ)_/¯
}
```

**Comment by kumavis** [comment]
better to use a single solution that's compatible across both

**Comment by rstormsf** [comment]
awesome!

**Comment by flyswatter** [comment]
Yeah that's a private method, it could be deprecated any time.

**Comment by phra** [comment]
@kumavis so which solution are you suggesting? i think we definitely need generic support for events..

**Comment by frankiebee** [comment]
@phra you should use the one in the guide https://github.com/MetaMask/faq/blob/master/DEVELOPERS.md#ear-listening-for-selected-account-changes
