### ISSUE TITLE
How to run smart contract without metamask in azure

### ISSUE THREAD

**Issue by mahan14** [MetaMask/faq#53]
Folks,

I am tying to create a nano service which will add a string and number through contract deployed in azure.
I am facing problem while connecting metamask to azure.
Any alternative or solutions?
Thanx in advance !!

**Comment by kumavis** [comment]
Look in the extension background.js network tab (not the ui tab) to provide us with some information to help debug. Please open an issue over at github.com/MetaMask/metamask-extension/issues/new
