### ISSUE TITLE
Fund not transfered

### ISSUE THREAD

**Issue by tnttony** [MetaMask/faq#55]
hi 

I tried sending ETH to an account yesterday and it is showing as send but its not reflecting in my balance amount. And when I try to send it again today it is saying as insufficient balance but I can see that there is balance left.

I checked in ehterscan using the MEtamask address and the transactions are not reflected there as well. Also How can I get the tnx id ?

PLease help!

**Comment by flyswatter** [comment]
Where did you send the ether from? If the block explorer does not show the transaction, it seems to have not happened. Is it possible the sending wallet/exchange had an issue sending?

**Comment by tnttony** [comment]
Sorry abt the confusion, i transferd the ether from bitoasis to metamask. that tnx is available in etherscan and the balance got reflected in metamask as well.

From metamask I tried sending it to another account like 3 times, all the time it shows as "send" but these tnx are not available in etherscan and the balance is still the same.This was yesterday, today I the balance is still the same but when trying to transfer it is telling me insufficient fund.

**Comment by tnttony** [comment]
Forget it.. it seems to be fine now!!  :)
