### ISSUE TITLE
Always getting ERR_CONTENT_LENGTH_MISMATCH

### ISSUE THREAD

**Issue by jw122** [MetaMask/faq#56]
I've deployed my contract with a UI to Ropsten via truffle and ran **npm run build** and **npm run dev** to start the server. As soon as I launch localhost (with the account in MetaMask selected), I get the following error and my dApp can't even show the balance in the account. 

`
GET http://localhost:8080/app.js net::ERR_CONTENT_LENGTH_MISMATCH`

It's happened in the past, but it would go away after a few refreshes. Now it's happening every time and I can't get my dApp to run as expected. Everything was tested and worked with testrpc.

**Comment by kumavis** [comment]
Weird. We'll need more data to help debug. please open an issue over at https://github.com/MetaMask/metamask-extension/issues/new
