### ISSUE TITLE
Clarification on installation docs

### ISSUE THREAD

**Issue by phahulin** [MetaMask/faq#57]
Hi everyone
I'm confused by the [installation instructions from faq](https://github.com/MetaMask/faq/blob/master/DEVELOPERS.md#partly_sunny-web3---ethereum-browser-environment-check)

1. It says:
> You can use the injected web3 directly, but the best practice is to replace it with the version of web3.js you used during development.

How exactly do I implement this best practice? The snippet there doesn't show it...
The way I read it, it looks like I need to import another copy (besides the one injected by MetaMask) of web3 library to my page and then use `Web3` from there and `web3.currentProvider` from metamask to create a new web3 object. It would also seem that I'd better not redefine existing `web3`.
So the full snippet would like this:
```html
<script src="https://example.com/web3.js"></script>
...
<script>
// create global object to use instead of metamask's web3
var my_web3;
window.addEventListener('load', function() {
  // Checking if Web3 has been injected by the browser (Mist/MetaMask)
  if (typeof web3 !== 'undefined') {
    // use another library's Web3
    var anotherWeb3 = require('web3');
    // and current provider from metamask
    my_web3 = new anotherWeb3(web3.currentProvider);
  }
  else {
    console.log('No web3? You should consider trying MetaMask!')
  }
});
</script>
```

2. And another question about the snippet in docs. Here
```javascript
window.web3 = new Web3(web3.currentProvider);
```
isn't `window.web3` the same thing as `web3`? What does this redefinition mean then?

**Comment by flyswatter** [comment]
Yes, `window.web3 === web3`, but `window.web3 !== new Web3()`, because `Web3 !== web3`.

**Comment by phahulin** [comment]
What about the 1st question?

2. I don't quite understand you...
Initially we have `web3` injected by metamask.
Then we use it to create a separate instance with `new Web3(web3.currentProvider)`.
And then we _assign it back_ to the original `window.web3 === web3`, so it looks like we redefine existing `web3` here.
Why do we do this, why not use the provided `web3`? This is probably related to the first question.

**Comment by abitrolly** [comment]
I was also confused, so I created #100 to fix this.
