### ISSUE TITLE
https://theethereum.wiki/ flagged as a phising address

### ISSUE THREAD

**Issue by PhABC** [MetaMask/faq#58]
The https://theethereum.wiki/ website is flagged as a phishing domain and Metamask is blocking it. However, I do not see this domain in the [EtherAddressLookup blacklist](https://github.com/409H/EtherAddressLookup/blob/master/blacklists/domains.json). 

Bug?

**Comment by Zanibas** [comment]
Addressing, the fuzzy logic needs some polishing!

**Comment by kumavis** [comment]
This should already be fixed -- maybe we should make a button to manually update the blacklist
