### ISSUE TITLE
Can't add existing account -using seed phrase- after creating new account.

### ISSUE THREAD

**Issue by joedope** [MetaMask/faq#59]
The plus button creates more new accounts, but there's no option to add an existing account using my password and pass phrase.
(Also there's no way to remove an account)

**Comment by tmashuang** [comment]
I believe one way to merge the two accounts temporarily would be to import an account's private key into the other. The imported account would be considered a loose account and would have to be added back using the same method in the event of account recovery. Details of loose accounts are here [Loose Accounts](https://github.com/MetaMask/faq/blob/master/USERS.md#loose-accounts).
The only way to current remove all accounts would be to go through the recovery account process. Lock Metamask through the drop down menu by clicking the top right icon, click Forgot Password, and input the 12-word seed phrase Metamask provided upon account creation. This will only show Account 1 after successfully restoring an account. Any addresses/accounts created before account recovery will be the same once the "+" button is clicked again to ensure that ETH is not lost on subsequent accounts.

**Comment by joedope** [comment]
Thank you. I'll recover password.

**Comment by skh666** [comment]
没有密钥了 没有种子了 怎么弄

**Comment by kumavis** [comment]
@skh666 没有密钥, 没有种子? 没办法 : (
请备份你的种子
