### ISSUE TITLE
Metamask token balances issue

### ISSUE THREAD

**Issue by alfa1983** [MetaMask/faq#61]
Hi
Unable to add tokens as clicking "TOKENS" button shows "There was a problem loading your token balances" error.
Tried on several PC`s

**Comment by Mateo94** [comment]
I am also exp this issue i believe it is tied to the new 0x token wasn't exp this prior.

**Comment by flyswatter** [comment]
Sorry, our token list is a little brittle right now, and our backend is a bit overloaded with people like yourself trying to add their new 0x tokens.

Try [connecting to a local node](https://support.metamask.io/kb/article/2-using-a-local-node), or just waiting a few hours until this traffic has relieved a bit.

**Comment by KazanGi** [comment]
Thanks for the info

**Comment by uworld66** [comment]
Why is this issue closed as it has not been resolved. I am having the same problem and can not remove error or view any tokens in metamask.

**Comment by uworld66** [comment]
my issue is with the REX token so I sent a few dent as a test they are also not visible. I can see them only via etherscan but can not remove the error or access tokens through metamask.
