### ISSUE TITLE
Error Message in token wallet

### ISSUE THREAD

**Issue by randy3pak** [MetaMask/faq#62]
"Token lists are temporarily down. You can check you your token balances here"
Can I still send to MEW or another address??

**Comment by flyswatter** [comment]
You can in fact use MEW with your MetaMask accounts, they recently became compatible!  Just visit [MEW](https://www.myetherwallet.com/), and on the `SEND` view, for account type, select MetaMask.

**Comment by randy3pak** [comment]
Thats great. Thanks for help. Meta is new to me thanks to 0xproject.
