### ISSUE TITLE
Cannot log into Metamask

### ISSUE THREAD

**Issue by haiqu** [MetaMask/faq#63]
Haven't used Metamask for some months. When I tried to log in today using what I am certain is the correct password, the spinning icon never stops and I don't gain access to my accounts. I note that the latest version seems to have been downloaded in the background and wonder whether some change has made it impossible to log in.

Platform: Windows 7 32-bit

Note: I have no idea where the keys are to restore this, and have a significant amount of Plutons held in this wallet. I can still see the public keys when on EtherDelta.

**Comment by flyswatter** [comment]
First off, let this be a big reminder to keep seed words backed up, especially for any account holding a state you don't want to lose. Computers fail all the time for all kinds of reasons.

You can help us debug this by checking the logs when you try to log in, there may be some red error text indicating what's wrong:
https://github.com/MetaMask/faq/blob/master/LOGS.md

After that, there may be other ways we can help you get through this.

**Comment by haiqu** [comment]
I did actually back up the keys but I have three computers, live on a yacht and sometime stay at my brother's place. Somehow I can't remember where I was when I installed it, and where I wrote or copied it to unfortunately.

Chrome background logs show no red errors. I'm thinking this may be an issue with the firewall and will investigate that aspect further, and although I can't recall changing it maybe a Win7 update has screwed something up.

**Comment by haiqu** [comment]
Popup logs->Console is very unresponsive, but all I can see there is a warning about the React package, which seems trivial. There are also 16 items hidden by the default filters but they must be even more trivial.

**Comment by flyswatter** [comment]
Have you tried restarting that browser or computer?

**Comment by haiqu** [comment]
Yes.

**Comment by haiqu** [comment]
Tried to move the data to a faster computer tonight, thinking that maybe the old core duo laptop might not be fast enough to cope with the latest version (see comment above about unresponsiveness).

Could not clone the data, new computer just over-writes the files. If I use Developer Mode->Load Unpacked Extensions it complains that the _metadata directory is system-only. Changing the name by removing the leading underscore didn't help either. It seems that all Google search data on cloning Metamask is bogus or out-of-date.

I'm running out of ideas here.

**Comment by flyswatter** [comment]
Sorry I forgot about this thread. We actually have a support system where we have much better management of open issues, I always recommend users open issues there.  https://support.metamask.io

Your best bet at saving those accounts may involve extracting them from the background. I recommend copying the vault data for unlocking outside of MetaMask later:
https://support.metamask.io/kb/article/22-how-to-copy-your-vault-data

**Comment by haiqu** [comment]
Well at least that allowed me to try it on another faster computer. Didn't help, it looks like I'm screwed.

Brilliant.

**Comment by flyswatter** [comment]
Sorry to hear that. We're going to make it harder to sign up without saving your seed words in the future, it's the most fundamental way a user can prevent this kind of loss.

**Comment by haiqu** [comment]
Did you read above where I said I did save it?

Key found at last. Second account with Plutons was not visible on the menu, so I restored it from the Private Key. Shows 0 tokens and 0.01 ETH only. Logo on dropdown menu has "Loose" printed over it.

There has been some major and apparently incompatible change in the past 366 days since this account was set up. The explorer shows my Plutons are at this address: 

0xfe61592Aa43BE1185fd8abfa54071727c47af474

but I can no longer access them through Metamask. Any ideas now?

**Comment by flyswatter** [comment]
Does this sound anything like it? https://medium.com/metamask/metamask-3-migration-guide-914b79533cdd

**Comment by flyswatter** [comment]
If you have any more problems, please submit them to support.metamask.io

This is our FAQ issues, it's intended for submitting issues with the FAQ itself.

**Comment by haiqu** [comment]
Found the issue. Token contract address had changed. Closed.
