### ISSUE TITLE
Please provide examples for web3.currentProvider

### ISSUE THREAD

**Issue by ftppro** [MetaMask/faq#70]
Please provide examples for web3.currentProvider, as requested here:
https://ethereum.stackexchange.com/questions/25962/please-provide-example-for-web3-currentprovider

**Comment by tegila** [comment]
Please, I'm trying to make this work for the last three days using metamask provider into web3 framework or even getting window.web3 from injected metamask.

But both returning errors like:
> web3.eth.accounts
[]

> web3.eth.getAccounts(accounts => console.log(accounts[0]))
undefined
US:34 Uncaught TypeError: Cannot read property '0' of null

Totally unstable =\

**Comment by danfinlay** [comment]
That’s not an instability, you’re using the API wrong.

The getAccounts method takes a node style callback, which includes an error as its first parameter. It’s not a promise.

There are more examples available at the bottom of this blog post: https://medium.com/metamask/metamask-hackathon-guide-a88a161416ce?source=linkShare-9cdd320de5c9-1509588490
