### ISSUE TITLE
How to add custom rpc params?

### ISSUE THREAD

**Issue by JohnAllen** [MetaMask/faq#72]
BTW, this seems different than #41. I'm not able to get any inputs -- when I click "Custom RPC" nothing happens. I don't get any inputs.

**Comment by flyswatter** [comment]
What kind of params are you talking about? Like HTTP Auth params, or query params? We don't currently support HTTP-Auth, although this has been requested on our main issues page, you can voice support there: https://github.com/MetaMask/metamask-extension/issues/1871

If you're having problems using MetaMask, you can get answers to those at support.metamask.io

**Comment by flyswatter** [comment]
Oh wait, nothing happens? It should take you to the settings page. Go ahead and peek in the UI logs: when you click that option, do you see any error? 
https://github.com/MetaMask/faq/blob/master/LOGS.md#popup-logs-chrome
