### ISSUE TITLE
MISSING ETHER: ETHER NOT SHOWING MY METAMASK BUT SHOWS IN ETHERSCAN AND MYETHERWALLET

### ISSUE THREAD

**Issue by woodae** [MetaMask/faq#73]
HI all

i have recently made a transaction to get fuel token, the transaction later disappear from etherscan. My token was deducted from metamask but not on etherscan. i did not receive the fuel token too.

Please see attached on this. Etherscan shows i have 9.999 eth but metamask shows that i have none. 

This is the transaction id in etherscan 
0x14331014f86e0a657c18a47633075566e989d027d5f2bc36144a591e7ce7d2a1

Etherscan
![snip20171002_32](https://user-images.githubusercontent.com/32453660/31075406-f0b2ac54-a7a7-11e7-8391-6d9c3f57b644.png)

Etherwallet
![meta scan error](https://user-images.githubusercontent.com/32453660/31075312-79f1ee68-a7a7-11e7-8fbc-6e61ee0712d2.png)

Below is the MetaMask State Logs

[MetaMask State Logs.txt](https://github.com/MetaMask/faq/files/1348773/MetaMask.State.Logs.txt)

Kindly help.

**Comment by tmashuang** [comment]
@woodae we have made changes to how balances are shown. please ensure that your Metamask version is updated to 3.10.9.
