### ISSUE TITLE
Lost 12 word phrase

### ISSUE THREAD

**Issue by jamikka1111** [MetaMask/faq#78]
Hi,

I had to redownload Meta Mask because it was not working properly. I seem to have misplaced my 12 phrase passcode. I do however have my private key and my password. Please let me know what I can do to recover my account.

**Comment by tmashuang** [comment]
If the seeds phrase to the associated vault is lost there is no way to import a single account without creating a new vault. Creating a new vault will provide the functionality to import an account with the private key. Doing so will not associate the new vault with the imported account. The private key will be the main recovery process until the associated seed phrase is recovered.

**Comment by jamikka1111** [comment]
Thank you very much
