### ISSUE TITLE
Bad Instructions

### ISSUE THREAD

**Issue by jamikka1111** [MetaMask/faq#79]
Hi,

I have been attempting to send ETH to a smart contract. I use a Gas Limit of 500,000 and GWEI of 20 I continue to get "Bad Instructions" what is wrong?

**Comment by danfinlay** [comment]
Bad instruction means there is an error with the smart contract, or the way you are calling it. There is not an easy way to debug this at the moment, other than asking the creators of that smart contract. We will always try to add easier ways of knowing what went wrong.
