### ISSUE TITLE
Integrating with nodejs dapp

### ISSUE THREAD

**Issue by nandinicbit1981** [MetaMask/faq#8]
Hello,
I am working on a nodejs web app with frontend in angular and backend(api's) on nodejs.
Is there a way to use metamask as authentication?

If so, are there any tutorials as in how to integrate metamask with my webapp?

I am not using truffle.

**Comment by kumavis** [comment]
Sorry we dont monitor issues on FAQ
Take a look at https://github.com/MetaMask/mascara
good luck
