### ISSUE TITLE
Import JSON file closes window on Firefox

### ISSUE THREAD

**Issue by wjmelements** [MetaMask/faq#80]
The workaround only works for chrome.

**Comment by Lionade** [comment]
I have the same issue. Did you find any solution yet?

**Comment by longnd** [comment]
I also have the same issue, click the Browse button to browse the json file, Firefox opens the file picker windows which close Metamask. It's really frustrating

**Comment by danfinlay** [comment]
Duplicate of https://github.com/MetaMask/metamask-extension/issues/2722 which links to a workaround.

 Since this is a browser bug, there’s nothing we can do for this until we allow the ability to open MetaMask in a full tab for forms like this.
