### ISSUE TITLE
Token transfer transactions are failing in Metamask

### ISSUE THREAD

**Issue by rshuk** [MetaMask/faq#84]
I have been trying to transfer tokens from one of my Metamask wallet address to another one since yesterday and am getting failed transactions.

I am experiencing issues like the "Metamask Notification" would take a lot of time to come up (4-5 mins and sometimes even more) and then when I click "Submit" in the notification to confirm the transaction, the notification pop-up will stay on the screen all in blank. In case it gets past that blank "Metamask Notification" box, then it would return failed transaction (see attached screenshot).
![887](https://user-images.githubusercontent.com/32688001/33540007-08129ce2-d8ef-11e7-9706-2dd656437b73.png)

**Comment by darthprime82** [comment]
same here! i tryed topping up with eth for transaction fee and also upped the gas fee? still same problem?

**Comment by Jknudsen14** [comment]
Same here cant do anything with my eth right now getting "RPC error with payload [...] insufficient funds for gas"

**Comment by danfinlay** [comment]
We've now written a post about this issue, please see if it helps: https://medium.com/metamask/metamask-cryptokitty-performance-update-83d851af0147

In short: We just gained nearly 100k users in two days, so forgive us while we scale up our backends, some tips in the article.

**Comment by Jknudsen14** [comment]
Sounds good. It started working again so you did something good ! thx and I
love meta mask

**Comment by Jknudsen14** [comment]
> Hi I bought some tokens from the naga ico (NGC) and wanted to hear if I
can just give Them my Meta mask wallet adress. The same adress I send ETH
to. The tokens are ERC-20.
