### ISSUE TITLE
How does Metamask store encrypted vaults 

### ISSUE THREAD

**Issue by Moejoe90** [MetaMask/faq#85]
I realized that at some point you guys used eth_lightwallet and then somehow abandoned it. 
I am wondering if there is any security reason for that, and what is a better alternative from your point

Additionally, how does meta-mask store encrypted vaults in the extension file,

**Comment by danfinlay** [comment]
Yeah, it had some issues:

https://medium.com/@alexberegszaszi/why-do-my-bip32-wallets-disagree-6f3254cc5846?source=linkShare-9cdd320de5c9-1512447635

We use our own npm packages browser-passworder, eth-simple-keyring, and eth-hd-keyring.

**Comment by Moejoe90** [comment]
Thanks for the prompt reply helpful indeed
