### ISSUE TITLE
Restored from Key Phrase But my wallets aren't there

### ISSUE THREAD

**Issue by dclancy13** [MetaMask/faq#86]
Heya
Hoping I didn't miss an important step in the process. Transactions kept failing with my MetaMask extension. I backed up the seed phrase and uninstalled / reinstalled the extension. When I tried to reload from my seed phrase it accepted it but is only showing 1 account (there were about 5) 
I am now missing a bunch of my accounts. 
Please help!
Thanks so much

**Comment by tmashuang** [comment]
You can re add the accounts by clicking Create Account, the accounts should re add in the same order.
