### ISSUE TITLE
ETH balance randomly changes when converting ETH/WETH & vice versa

### ISSUE THREAD

**Issue by MarcZenn** [MetaMask/faq#88]
I've noticed that if you say, have 1.78938 ETH and you convert .1 of that ETH to WETH on Kovan, every once in a while the ETH balances listed in the MM chrome plugin will randomly change from 1.7 to 1.8 to 1.6 etc about every 3-5 seconds or so and this continues even after tx is mined and a receipt is returned. Eventually it does show the correct balance but it's strange to see these seemingly random fluctuations.

**Comment by danfinlay** [comment]
By default, MetaMask does state lookups against Infura, which is a load-balanced cluster of ethereum clients. What you're seeing is the balance gradually sync across those nodes. I'm not sure what would be technically required to prevent this behavior, other than simply keeping a current state of account balance via a merkle proof, but I agree it's confusing and we should find a way to fix it.

Oh, also, this should be opened over here instead:

https://github.com/MetaMask/metamask-extension/issues

**Comment by danfinlay** [comment]
Closing in favor of https://github.com/MetaMask/metamask-extension/issues/2674
