### ISSUE TITLE
Slow Transfer in to Metamask

### ISSUE THREAD

**Issue by Chris-1234** [MetaMask/faq#89]
Hi guys
I have transferred btc to my Metamask and it has still not appeared in my Metamask account. Was wondering if there is a possible reason for this delay (17 hours) and if it is possible to track my transfer.
Thanks

**Comment by danfinlay** [comment]
How did you send BTC to MetaMask? I assume you used ShapeShift? Have you checked with them?

**Comment by Chris-1234** [comment]
Hi Dan

Sent from coinspot to my metamask wallet address.



Sent from my iPhone

On 6 Dec 2017, at 12:37 pm, Dan Finlay <notifications@github.com<mailto:notifications@github.com>> wrote:


How did you send BTC to MetaMask? I assume you used ShapeShift? Have you checked with them?

**Comment by danfinlay** [comment]
MetaMask can't store Bitcoin, and bitcoin clients should not be able to send to Ethereum addresses. You should check what address you sent to from Coinspot. I assume it has a transaction history?

**Comment by Chris-1234** [comment]
There is a transaction history, The address is my metamask wallet address. In this case the, where would the BTC of gone?

**Comment by danfinlay** [comment]
I don't know. You should ask Coinspot.

**Comment by Chris-1234** [comment]
ok thankyou Dan.
