### ISSUE TITLE
Sorry, We are unable to locate the Transaction Hash

### ISSUE THREAD

**Issue by samuelswinslow** [MetaMask/faq#90]
Congrats on the tens of thousands of new users in the last few days! Once Eth gets cats, the masses show up.

Any idea why transactions aren't working at the moment? I need to make a critical, time sensitive transfer ASAP.

Thanks in advance!

**Comment by danfinlay** [comment]
Yes, it's as simple as many transactions in the backlog. Anyone can get a transaction processed by simply bidding a high enough gas price. [EthGasStation](https://ethgasstation.info/) is suggesting as much as 30 gwei.

More depth here:
https://medium.com/metamask/metamask-cryptokitty-performance-update-83d851af0147

**Comment by samuelswinslow** [comment]
Dope!

Thank you sir. I did 80 gwei on the transaction that I'm most concerned with, and so I should expect to see it sometime in the next 24 hrs?

Thanks again!
