### ISSUE TITLE
please help Metamask error Failed: rpc error with payload.Error Transaction underpriced

### ISSUE THREAD

**Issue by myetherdomain** [MetaMask/faq#91]
Hi,
I want to reveal a bid for an ENS domain, but Metamask keeps giving me errors :( 
Please help, as I want to be able to reveal my bid in time.  

Error: [ethjs-rpc] rpc error with payload
Error: transaction underpriced

I tried to reveal the bid again, with a higher gas price. Then it shows me a warning, and the transaction stays on Pending for a long time and seems to disappear later. 
(see 0x377488a39ecb1b1dd517aeeed5716446361f937caaab8593e3ce85a38de02570, currently pending status)

Any advise how to solve this? 
Thanks in advance for your help!

**Comment by danfinlay** [comment]
Yes, it's as simple as many transactions in the backlog. Anyone can get a transaction processed by simply bidding a high enough gas price. [EthGasStation](https://ethgasstation.info/) is suggesting as much as 30 gwei.

More depth here:
https://medium.com/metamask/metamask-cryptokitty-performance-update-83d851af0147

**Comment by myetherdomain** [comment]
Thanks danfinlay, 
But it's not the solution here I'm afraid. I used a gasprice of 30 gwei, but it's still on Pending state after more than 30 minutes now. 
You can see the transaction here:  https://etherscan.io/tx/0x377488a39ecb1b1dd517aeeed5716446361f937caaab8593e3ce85a38de02570

Just want to make a new transaction so that I can reveal my bids today.

**Comment by bisratyalew** [comment]
Hi,

I got an error while i was trying to buy token from Ropsten faucet

{"error":"[ethjs-rpc] rpc error with payload {\"id\":4700841027252,\"jsonrpc\":\"2.0\",\"params\":[{\"to\":\"0x524f7a0150a47f0f60b87d5f8c9e0d79a420ec9a\",\"from\":\"0x81b7e08f65bdf5648606c89998a9cc8164397647\",\"value\":\"0xde0b6b3a7640000\",\"data\":\"0x\"}],\"method\":\"eth_sendTransaction\"} [object Object]"}

How can i fix this error?
