### ISSUE TITLE
Better web3 detection and fallback

### ISSUE THREAD

**Issue by bwheeler96** [MetaMask/faq#92]
Hey y'all, the web3.js fallback strategy in the DEVELOPERS.md leaves a little bit to be desired.

I created a gist here https://gist.github.com/bwheeler96/5ad85254168b1aa5f7e808db50b0287b. This is being used to create the experience at https://ddx-demo.optimum.network

Basically:

- Detects web3 if injected before window.load
- If no web3 before window.load, check again after window.load
- If no web3 at all, load it and provider from provided URLs, then run a fallback function

It has the main advantage of
- Not making web3-enabled users download web3 if they don't need to
- Not making web3-enabled users necessarily wait for window.load
- Enabling a "fallback experience" for newcomers that can direct them to "intro" pages or similar

I don't really have a goal for where I want this to go, but I figured I'd try and save the next dev an hour or to with this

**Comment by kumavis** [comment]
nice! also take a look at https://github.com/MetaMask/mascara
