### ISSUE TITLE
Transactions not displayed / transaction list failing to update

### ISSUE THREAD

**Issue by jdetychey** [MetaMask/faq#93]
Hello, 
Since the kitty craze the list of sent transactions is not updating in the extension (last tx showed in the list was the 3rd of Dec.). 
Is there a way to refresh or reset the list?

The extension is still working pretty well, good job to the team <3.

Insert cool fox gif:
[image] [https://i.imgur.com/QaNH1ao.gifv](https://i.imgur.com/QaNH1ao.gifv) [/image]

**Comment by kumavis** [comment]
metamask does not import incomming transactions of transactions made from another device


if you still have questions, please email support@metamask.io
