### ISSUE TITLE
Delete or edit custom token?

### ISSUE THREAD

**Issue by cannonlinc** [MetaMask/faq#94]
I am new to github (I am not a developer), still figuring this out...

I am using Metamask with the Brave browser. I bought 88,000 bitdegree (BDG) tokens (tranferred 8 ether) in their ico, and then tired to add BDG as a custom token in my Metamask wallet, but I must have done it incorrectly. Etherscan.io correctly shows the transaction, but my Metamask doesn't correctly recognize the BDG token I created. It shows 80000000000.000 BDG in my Metamask wallet, but the token is not associated with any transactions in etherscan.io

Can I delete or somehow edit the custom BDG token so that it correctly connects with the 88,000 BDG? 

Any help would be appreciated, I will check back here periodically or you can contact me for more info at cannonlinc@gmail.com

![bgd problem](https://user-images.githubusercontent.com/33463044/33805477-739735c6-dd6e-11e7-9146-f2bb43e7e200.PNG)

[MetaMask State Logs.txt](https://github.com/MetaMask/faq/files/1545700/MetaMask.State.Logs.txt)

**Comment by danfinlay** [comment]
No, sorry, we need to upgrade our token management. The workaround until then is to back up your seed phrase and reinstall MetaMask.

**Comment by cannonlinc** [comment]
Ok, thanks for the reply. 


Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: Dan Finlay <notifications@github.com> Date: 12/10/17  10:53 AM  (GMT-08:00) To: MetaMask/faq <faq@noreply.github.com> Cc: cannonlinc <cannonlinc@gmail.com>, Author <author@noreply.github.com> Subject: Re: [MetaMask/faq] Delete or edit custom token? (#94) 
No, sorry, we need to upgrade our token management. The workaround until then is to back up your seed phrase and reinstall MetaMask.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/MetaMask/faq","title":"MetaMask/faq","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/MetaMask/faq"}},"updates":{"snippets":[{"icon":"PERSON","message":"@danfinlay in #94: No, sorry, we need to upgrade our token management. The workaround until then is to back up your seed phrase and reinstall MetaMask."}],"action":{"name":"View Issue","url":"https://github.com/MetaMask/faq/issues/94#issuecomment-350570055"}}}

**Comment by cannonlinc** [comment]
Thanks. So I didn’t see any option to reinstall metamask in brave, do I need to uninstall and reinstall the whole browser?

Sent from Mail for Windows 10

**Comment by cannonlinc** [comment]
Instead of doing a Metamask reinstall in Brave (which I still can’t figure out how to do)  if I just leave everything as is, I will  be able to access the token via Metamask once token management  is upgraded (correct?)  Any timeline for that?

Sent from Mail for Windows 10

From: Excitable Boy
Sent: Monday, December 11, 2017 12:45 PM
To: MetaMask/faq
Subject: RE: [MetaMask/faq] Delete or edit custom token? (#94)

Thanks. So I didn’t see any option to reinstall metamask in brave, do I need to uninstall and reinstall the whole browser?

Sent from Mail for Windows 10

**Comment by danfinlay** [comment]
Yes, I would say so. Also, you can still interact with tokens you have via other interfaces, like myetherwallet.com

**Comment by cannonlinc** [comment]
Ok, thanks. I’m s little confused as to how MEW and Metamask interact, e.g., I have sent ether from Metamask to MEW and it shows up in Mew but not in Metamask, hwile the coins in Metamask don’t show up in my MEW, they seem to shoe up in only one place or the other and the BDG can’t be sent from Metamask since it is incorrectly configured. I’m still figuring all of this out, what seems like an endless learning curve. Anyway, thanks for the response, I’ll try to figure it out

Sent from Mail for Windows 10

**Comment by Filoz** [comment]
@danfinlay have you got an ETA for that upgrade?

Thank you for metaMask :)

**Comment by King-of-Limbs** [comment]
An option to edit or delete is really needed since I mistyped and now have a useless 0-Token in there I can't get deleted. Thanks for the effort!

**Comment by danfinlay** [comment]
Ability to edit is fixed in master and coming with next release.

**Comment by austinyearlykim** [comment]
can't wait.

**Comment by bvallelunga** [comment]
Any updates when it be released?

**Comment by danfinlay** [comment]
Early next week at the latest.

**Comment by cannonlinc** [comment]
Good to  hear. 

One question: once released, will the update be automatic with the next update of Brave, or do I have to figure out how to update Metamask within Brave.

Thanks.

Sent from Mail for Windows 10

**Comment by danielwhatmuff** [comment]
looking forward to this! +1

**Comment by danfinlay** [comment]
Update will be automatic, probably later today or tomorrow.

**Comment by cannonlinc** [comment]
Great,  thanks!


Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: Dan Finlay <notifications@github.com> Date: 1/8/18  4:31 PM  (GMT-08:00) To: MetaMask/faq <faq@noreply.github.com> Cc: cannonlinc <cannonlinc@gmail.com>, Author <author@noreply.github.com> Subject: Re: [MetaMask/faq] Delete or edit custom token? (#94) 
Update will be automatic, probably later today or tomorrow.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/MetaMask/faq","title":"MetaMask/faq","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/MetaMask/faq"}},"updates":{"snippets":[{"icon":"PERSON","message":"@danfinlay in #94: Update will be automatic, probably later today or tomorrow."}],"action":{"name":"View Issue","url":"https://github.com/MetaMask/faq/issues/94#issuecomment-356141284"}}}

**Comment by meenie** [comment]
Any update on the update? :)

**Comment by meenie** [comment]
@danfinlay I thought the update would include the ability to delete custom tokens but I'm not seeing how that can be done... This is what I'm seeing:

![image](https://user-images.githubusercontent.com/1126819/35234558-70d4b750-ff56-11e7-9e90-e13868097920.png)

If I click on the token it just takes me to the etherscan.io page.

**Comment by cannonlinc** [comment]
Dan,

Still having all kinds of issues:
(1) I have 999.38 OMG, not 999938000000000.000
(2) I have two BDG tokens, 148000.000 (correct), 1400000000000.000 (unknown, token has no value, I added this one accidentally, can’t get rid of it?)
(3) I have two COV tokens, 160.16 (correct), 0 (unknown, no token value, I didn’t add this, it just showed up in metamask a couple of days ago)
(4) ICN (a legitimate token according to etherscan) , just showed up in my metamask a couple of days ago, but I don’t have any  ICN and I didn’t add the token.

I still can’t figure out how to delete illegitimate (BDG & COV) or legitimate (ICN) tokens. Also don’t know how to fix the OMG display problem.

I am using the Brave browser, and I am assuming Metamask updates are incorporated into brave updates? If not, please explain how to update Metamask within Brave

I love Metamask, but these ongoing glitches make me nervous.

Any help would be appreciated.

Sent from Mail for Windows 10

**Comment by danfinlay** [comment]
No, sorry, the ability to remove tokens is being tracked in another issue:
https://github.com/MetaMask/metamask-extension/issues/2910

**Comment by danfinlay** [comment]
Furthermore, we have a new UI coming out soon, which already features token removing, so we may not add it to the current UI, and just let the new UI handle this.

**Comment by danfinlay** [comment]
@cannonlinc If you're having specific problems with a token, please email the details including [state logs](http://metamask.helpscoutdocs.com/article/9-how-to-download-state-logs) to support@metamask.io

**Comment by cannonlinc** [comment]
Ok, thanks.

Sent from Mail for Windows 10

**Comment by afdalky** [comment]
Guys any ETA on the new release?

**Comment by danfinlay** [comment]
Later in the month. Watch for a beta option in the top right menu.

**Comment by vindiou** [comment]
Hi,
Me too! I have mistakenly have added a custom token that I can't remove!!!
Thanx!!

**Comment by MMaynard31** [comment]
Hi i have mistakenly added a wrong token name how do i remove

**Comment by farizluqman** [comment]
any updates?

**Comment by MMaynard31** [comment]
Nothing yet
