### ISSUE TITLE
Metamask / EtherDelta transaction rejected

### ISSUE THREAD

**Issue by skim4045** [MetaMask/faq#97]
I used Metamask to send ETH to EtherDelta to trade. And I placed an order to exchange ETH for another coin (KIN).

Soon after the transaction went through at EtherDelta, I saw a pop up and it disappeared instantly. Then I saw an alert icon at Metamask.  It was asking me to confirm something.  And not realizing it was related to my trade at EtherDelta, I rejected it. 

Now I don’t see the KIN coin anywhere while my ETH used to purchase it is gone.  

I understand  that the transaction was successful at EtherDelta, but I am guessing one of the confirmations required is rejected (by me). 

Even then, because the tx would’ve received enough confirmations so the tx should be valid.  

Is there anyway I can get the KIN coin deposited into my wallet? Or if the tx is rejected, shouldn’t I receive my ETH back?

**Comment by kumavis** [comment]
if you still have questions, please email support@metamask.io
